version: 2
sources:
- name: "{{env_var('DATABASE_SCHEMA', var('source_schema', ''))}}"
  schema: "{{env_var('DATABASE_SCHEMA', var('source_schema', ''))}}"
  quoting:
    database: false
    schema: false
    identifier: false
  loader: stitch
  tables:
  - name: merchant_listing
  - name: fba_fulfillment